language: node_js
node_js: "9"
notifications:
  email: false

# From: https://www.electron.build/multi-platform-build
# example: https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml
stages:
  - stage: test
    script:
      - yarn test --coverage
      - yarn lint
    os: linux
    language: node_js
  - stage: release
    if: branch = master
    os: linux
    services: docker
    language: generic
    script:
      - docker run --rm \
          --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
          -v ${PWD}:/project \
          -v ~/.cache/electron:/root/.cache/electron \
          -v ~/.cache/electron-builder:/root/.cache/electron-builder \
          electronuserland/builder:wine \
          /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn release-all"

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
